# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.10.0.schema.json

PackageIdentifier: Microsoft.GlobalSecureAccessClient
PackageVersion: 2.18.62.0
InstallerType: exe
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /install /quiet /norestart
  SilentWithProgress: /passive /install
Installers:
- Architecture: x64
  Scope: machine
  InstallerUrl: https://download.msappproxy.net/Subscription/b8795d5c-2a52-4259-9dc9-bff6eb3e15d7/Connector/GlobalSecureAccessClientInstaller
  InstallerSha256: 118BB99FD83C9C524326A7A67B303D3C19D145791D0C5804A8E002C4FCB7B676
  ProductCode: '{1DAEB231-635C-4804-ADC5-54181C39C229}'
  ElevationRequirement: elevationRequired
ManifestType: installer
ManifestVersion: 1.10.0