# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: VMware.Tools
PackageVersion: 12.5.2.24697584
InstallerType: exe
InstallerSwitches:
  Silent: /s /v/qn REBOOT=ReallySuppress EULAS_AGREED=1
  SilentWithProgress: /s /v/qb REBOOT=ReallySuppress EULAS_AGREED=1
Installers:
- Architecture: x64
  InstallerUrl: https://packages.vmware.com/tools/esx/latest/windows/x64/VMware-tools-12.5.2-24697584-x64.exe
  InstallerSha256: 82B73DB5306BBA253F885FE2E6EEA18849AA52F0A3DA827E2B4EE876930EA505
ManifestType: installer
ManifestVersion: 1.10.0
