# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Nvidia.App
PackageVersion: 11.0.4.526
PackageLocale: en-US
Publisher: NVIDIA Corporation
PublisherUrl: https://www.nvidia.com/
PrivacyUrl: https://www.nvidia.com/en-us/about-nvidia/privacy-policy
PackageName: NVIDIA App
PackageUrl: https://www.nvidia.com/en-us/software/nvidia-app/
License: Proprietary
LicenseUrl: https://www.nvidia.com/en-us/geforce-now/terms-of-use
Copyright: Copyright © 2011-2025 NVIDIA Corporation
CopyrightUrl: https://www.nvidia.com/en-us/about-nvidia/legal-info
ShortDescription: The NVIDIA App is the essential companion for PC gamers and creators. Keep your PC up to date with the latest NVIDIA drivers and technology.
Description: |-
    The NVIDIA App is the essential companion for PC gamers and creators. Keep your PC up to date with the latest NVIDIA drivers and technology.
    Optimize games and applications with a new unified GPU control center, capture your favorite moments with powerful recording tools through the in-game overlay, and discover the latest NVIDIA tools and software.
Tags:
- graphic
- game
- driver
- gaming
Documentations:
- DocumentLabel: FAQ
  DocumentUrl: https://nvidia.custhelp.com/app/answers/detail/a_id/5521/~/nvidia-app-faq
ManifestType: defaultLocale
ManifestVersion: 1.10.0
