PackageIdentifier: HWgroup.Hercules
PackageVersion: 3.2.8
PackageLocale: en-US
Publisher: HW group s.r.o.
PublisherUrl: https://www.hw-group.com/
PublisherSupportUrl: https://www.hw-group.com/support
PackageName: WiGui
PackageUrl: https://www.hw-group.com/software/hercules-setup-utility
License: Freeware
Copyright: HW group s.r.o.
ShortDescription: Hercules SETUP utility is useful serial port terminal (RS-485 or RS-232 terminal), UDP/IP terminal and TCP/IP Client Server terminal.
ReleaseNotesUrl: https://www.hw-group.com/product-version/hercules
ManifestType: defaultLocale
ManifestVersion: 1.10.0