# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: iSpring.iSpring.Free
PackageVersion: 11.3.6009
PackageLocale: en-US
Publisher: iSpring Solutions, Inc.
PackageName: iSpring Free
License: proprietary
ShortDescription: Create professional courses easily with iSpring. This is the Free Demo version.
ManifestType: defaultLocale
ManifestVersion: 1.10.0
