# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
# Latest download URL: https://www.mindmanager.com/mm-win-enterprise-admin-64

PackageIdentifier: Corel.MindManager.25
PackageVersion: 25.0.208.0
MinimumOSVersion: 10.0.0.0
Scope: machine
UpgradeBehavior: install
InstallerSuccessCodes:
- 1641
- 3010
- -1978335226
- 1603
Installers:
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: msi
  NestedInstallerFiles:
  - RelativeFilePath: MindManager 23.msi
  InstallerUrl: https://download.mindjet.com/MindManager_64bit_25.0.208_Admin.zip
  InstallerSha256: 967C24F8F8DD0C27A5923B56AC67E9C23A9102B4907583836FE56A27A27B7ED5
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.DotNet.Framework.DeveloperPack_4
    - PackageIdentifier: Microsoft.EdgeWebView2Runtime
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
  ProductCode: '{CD37F6A3-9C52-4931-B972-B35A0C3940CE}'
ManifestType: installer
ManifestVersion: 1.10.0