# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Lenovo.Vantage
PackageVersion: 10.2501.15.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: msix
PackageFamilyName: E046963F.LenovoSettingsforEnterprise_k1h2ywk1493x8
Installers:
- Architecture: x64
  InstallerUrl: https://download.lenovo.com/pccbbs/thinkvantage_en/metroapps/Vantage/LenovoCommercialVantage_10.2501.15.0_v3.zip
  InstallerSha256: B5F51FF02CF6C1BA96E4151316727BFC95B2C57413C716CE960AB4E9DE6B1261
  SignatureSha256: 1EF936315A2AC7FC326E18709D1F5C314EEC2670411FFAFD5E27BD809BA61036
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2025-01-08
